### ISSUE TITLE
Text extraction shoul be refactored

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.texttospeech#25]
Some initial thoughts on how to enhance the speech synthesis:

- ignore any tag that is hidden (not visible)
- validate `<script>` and `<iframe>` tags are ignored
- add a period character (`.`) after any text that is not ending with one, as is currently the case with the title and the description of an item

Here an example on how to select the text in a better way: http://stackoverflow.com/a/4399718/644075

We need to test the resulting code.

**Comment by rodfersou** [comment]
- [ ] ignore any tag that is hidden (not visible)
  * I can add an extra validation here
- [x] validate ``<script>`` and ``<iframe>`` tags are ignored
  * The css selector used in the jquery expression takes just the title, the description and the paragraphs today.
- [x] add a period character ``(.)`` after any text that is not ending with one, as is currently the case with the title and the description of an item
  * Today I create an array with the title, description and paragraphs and take out all ending periods.  After that I join this array with ``' .'`` (space and period) what add the periods needed.
