### ISSUE TITLE
Could not load ResponsiveVoice library

### ISSUE THREAD

**Issue by rafaeltcc** [collective/collective.texttospeech#35]
Hi,

What can I do when I get  Could not load ResponsiveVoice library" when accessing the configlet?

I tried diferent browsers. Do I need to install this library somewhere? Maybe with pip? Or is it bundled with the product?

Thanks,

Rafael

**Comment by hvelarde** [comment]
IIRC, that can happen if you have incorrect order on resource registries, no access to the CDN, or if you have installed some ad blocker.

the JS is registered here: https://github.com/collective/collective.texttospeech/blob/master/src/collective/texttospeech/profiles/default/jsregistry.xml

@rodfersou you remember this issue?

**Comment by rodfersou** [comment]
@hvelarde you are right, this resource is loaded from responsive voice site, and if the site is not accessible the message show up.
